"""String names used for array dimensions and coordinates."""

DAY_STR = "day"
DAY_OF_YEAR_STR = "day_of_year"
LAT_STR = "lat"
LON_STR = "lon"
LEV_STR = "plev"
PFULL_STR = "pfull"
P_SFC_STR = "p_sfc"
SFC_AREA_STR = "sfc_area"
SIGMA_STR = "sigma"
TIME_STR = "time"
YEAR_STR = "year"
Z_STR = "z"
