"""String names used for array dimensions and coordinates."""

BOUNDS_STR = "bounds"
DAY_STR = "day"
DAY_OF_YEAR_STR = "day_of_year"
LAND_MASK_STR = "land_mask"
LAT_BOUNDS_STR = "lat_bounds"
LAT_STR = "lat"
LON_BOUNDS_STR = "lon_bounds"
LON_STR = "lon"
LEV_STR = "plev"
P_SFC_STR = "p_sfc"
PFULL_STR = "pfull"
PHALF_STR = "phalf"
SFC_AREA_STR = "sfc_area"
SIGMA_STR = "sigma"
TIME_STR = "time"
YEAR_STR = "year"
Z_STR = "z"
